    --CREATE TABLE TASKS
CREATE TABLE tasks(
    id INTEGER PRIMARY KEY  AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(255),
    done BOOLEAN NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);